version: 0.2

env:
  # These secrets come from Secrets Manager Parameter Store.
  parameter-store:
    DOCKERHUB_TOKEN:  DOCKERHUB_TOKEN
#    CODECOV_TOKEN: CODECOV_TOKEN  # CodeBuild will retrieve this from Systems Manager Parameter Store.


phases:
  install:
    runtime-versions:
      docker: 18
      java: openjdk8
    commands:
      # Get information about this image, the current directory, maven version, docker version, then update apt-get.
      - lsb_release -a
      - pwd
      - mvn --version
      - docker --version
      - docker info
      - apt-get update

  pre_build:
    commands:
      # Get project's version from pom.xml.
      PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)

      # Copy custom maven settings from S3 bucket.
      aws s3 cp s3://maven-build-settings/qb4j_settings.xml /root/.m2/settings.xml

      # Check if the image exists in docker hub already.
      IMAGE_EXISTS=$(docker pull joneschris/qb4j-mvc:"$PROJECT_VERSION" > /dev/null && echo "true" || echo "false")
      echo "Does the image exist?  $IMAGE_EXISTS"

  build:
    commands:
      - bash ./cicd/buildspec_steps/0_build.bash "$IMAGE_EXISTS"

  post_build:
    commands:
      - bash ./cicd/buildspec_steps/1_post_build.bash "$DOCKERHUB_TOKEN" "$PROJECT_VERSION" "$IMAGE_EXISTS"



artifacts:
  files:
    - target/querybuilder4jmvc-$PROJECT_VERSION.jar
  name: querybuilder4jmvc
  discard-paths: yes
#  secondary-artifacts:
#    code_coverage:
#      files:
#        - target/site/jacoco/**/*  # All files recursively in jacoco directory.
#      name: code_coverage.zip
cache:
  paths:
    - '/root/.m2/**/*'
